### ISSUE TITLE
How to run this on windows?

### ISSUE THREAD

**Issue by AirForce101HD** [mattimustang/optus-sagemcom-fast-3864-hacks#1]
How do i run this using windows version of python?

**Comment by mattimustang** [comment]
Hi,

You will need to download and install [python 3.5](https://www.python.org/downloads/). Make sure you check the box to add Python to your PATH in the installer.

Then open a DOS or PowerShell command shell and install the pycrypto module:

    pip install --use-wheel --no-index --find-links=https://github.com/sfbahr/PyCrypto-Wheels/raw/master/pycrypto-2.6.1-cp35-none-win32.whl pycrypto

Download the [`decrypt-conf.py`](https://raw.githubusercontent.com/mattimustang/optus-sagemcom-fast-3864-hacks/master/decrypt-conf.py) script and you `backupsettings.conf` from your modem and put them in the same directory.

From the DOS/PowerShell window `cd` to the directory you saved these files in and run:

    python.exe decrypt-conf.py backupsettings.conf

This will create decrypted file `backupsettings.conf.txt`

**Comment by archienz** [comment]
Howdy, i am actually getting this on linux aswell as windows.

> pip :   Could not find a version that satisfies the requirement pycrypto (from versions: )
At line:1 char:1
+ pip install --use-wheel --no-index --find-links=https://github.com/sf ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (  Could not fin...rom versions: ):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
No matching distribution found for pycrypto

>

**Comment by archienz** [comment]
For Anyone wanting to know how to use it on windows, first install

Python 3.3
https://www.python.org/download/releases/3.3.0/

then from this website
http://www.voidspace.org.uk/python/modules.shtml#pycrypto
download PyCrypto 2.6 for Python 3.3 32bit

use CMD and cd/navigate into the directory you downloaded the files into and run the commands.
