### ISSUE TITLE
Output is not decrypted 

### ISSUE THREAD

**Issue by konashevich** [mattimustang/optus-sagemcom-fast-3864-hacks#13]
I am getting a still encrypted file as an output of this script. It seems it does not work. The original one is in the attachment 
[backupsettings.zip](https://github.com/mattimustang/optus-sagemcom-fast-3864-hacks/files/2791345/backupsettings.zip)

**Comment by mattimustang** [comment]
which firmware version do you have?

**Comment by konashevich** [comment]
*Board ID:F@ST3864V2Symmetric CPU Threads:2HardWare Version:253561846Serial
Number:N7172902J001060Mac Address:18:90:d8:ac:b7:efBuild
Timestamp:180623_1623Software Version:8.353.21_F@ST5350_OptusBootloader
(CFE) Version:8.353.1DSL PHY and Driver Version:A2pv6F039x6.d26rWireless
Driver Version:6.37.14.4803.cpe4.14L04.0-kdbVoice Service
Version:VoiceUptime:11D 17H 39M 13SConfigId:F5350_Optus_11.conf *


Kind regards,
Oleksii

пн, 11 февр. 2019 г. в 16:55, Matthew Flanagan <notifications@github.com>:

**Comment by LiamBogur** [comment]
I'm having the same issue, nothing is working, can you please try fix it?

**Comment by Zephyr-Wrangler** [comment]
I also have this issue.

Board ID:	F@ST3864V3AC
Symmetric CPU Threads: 2
HardWare Version: 253712055-C
Serial Number: <redacted>
Mac Address: <redacted>
Build Timestamp: 180523_1514
Software Version: 10.54_F@ST3864V3AC_Optus
Bootloader (CFE) Version: 10.54
DSL PHY and Driver Version: A2pv6F039x6.d26r
Wireless Driver Version: 1.366 RC5.0
Voice Service Version: Voice
Uptime: 0D 3H 48M 21S
ConfigId: F3864V3AC_Optus_5.conf

As do others at this thread:
https://forums.whirlpool.net.au/archive/2401743

**Comment by mattimustang** [comment]
Please see the 'Known Working Firmware Versions' section of the README . Sorry I can't do anything to help as I don't have a modem with the same firmware version. See also this issue for some tips I gave to try and help https://github.com/mattimustang/optus-sagemcom-fast-3864-hacks/issues/12

**Comment by Zephyr-Wrangler** [comment]
No worries, thanks any way.
