### ISSUE TITLE
Fix for slow upload speeds when bridging

### ISSUE THREAD

**Issue by KaHooli** [mattimustang/optus-sagemcom-fast-3864-hacks#5]
I have 100/40 (upload/download) FTTN speed with Optus FTTN NBN.

When reset the modem/router to factory defaults, I get about 77/33 (not too bad considering still using copper between home and node), but when I follow the Bridging steps I was getting 77/0.5.

I found that no change happened when I disabled QoS (under Advanced Setup -> Quality of Service), but if I went under the sub-menu option of QoS Port Shaping and set the Shaping Rate for all Interfaces to Disabled, my upload speed issue was fixed.

**Comment by mattimustang** [comment]
Hi @KaHooli,

Thanks for the info. Was your modem syncing at 100/40 or 77/33? What about max attainable? I had an issue where I was in bridge mode and upgraded from 25/5 to 50/20 and the modem synced at the 50/20 (and max attainable was 60/36) but speed tests told me I was getting about 50/5.

I called optus support and they reset the port at their end, I rebooted my modem and it all came good.

cheers
