### ISSUE TITLE
http://admin:"password"@192.168.0.1/main.html not working

### ISSUE THREAD

**Issue by Stark003** [mattimustang/optus-sagemcom-fast-3864-hacks#6]
Completed decryption of settings and found pass code except that when I enter  http://admin:"password"@192.168.0.1/main.html it presents a pop-up box prompting me to input my details. the username "root" and "admin" along with the decrypted password do not result in success.
I have the :
F@ST3864V2
with version:
8.353.1_F@ST5350_Optus

**Comment by mattimustang** [comment]
Try just connecting to http://192.168.0.1/main.html and entering user "admin" and the decrypted password.
