### ISSUE TITLE
NBN Bridge Mode: Waiting for ISP

### ISSUE THREAD

**Issue by alexisbmills** [mattimustang/optus-sagemcom-fast-3864-hacks#7]
After following the instructions, for NBN bridge mode, the Sagemcom web user interface has a yellow Internet status "Waiting for ISP". The physical modem displays a solid DSL light, but the Internet light does not light up. Is there anything else required?

**Comment by kronicd** [comment]
That is what you're after for bridge mode.

Plug in and configure your router

**Comment by mattimustang** [comment]
@kronicd is right. Your link is up. Plugin your preferred router with DHCP client enabled on the interface you connect to the optus modem.

**Comment by alexisbmills** [comment]
I'm having some trouble getting this working with my Asus router. In WAN settings, I set:
- connection type PPPoE
- Yes to get WAN IP automatically
- DNS servers 8.8.8.8, 8.8.4.4
- all other options as default

One part I'm not 100% sure about is the username/password. I've tried the credentials sent to me for the webmail, had Optus reset that password and tried it again.

**Comment by virtual812** [comment]
Instead of pppoe use ipoe
For NBN no username or password should be required.
