### ISSUE TITLE
Modify the DNS settings on F@ST 3864AC 

### ISSUE THREAD

**Issue by jasonbrimblecombe** [mattimustang/optus-sagemcom-fast-3864-hacks#9]
Are you able to locate the configuration to override the DNS server IP?
The Optus firmware restricts changing the address, and has defaulted it to 198.142.152.164/165 (Optus DNS servers).

**Comment by mattimustang** [comment]
Hi, If you login to the modem as admin and go to the Advanced Setup/DNS/DNS Server section of the menu you can change the DNS servers.
